name: Deploy to Prod
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Assume deployment role
        uses: youyo/awscredswrap@v1
        with:
          role_arn: arn:aws:iam::019181405815:role/helloworld-deployment-role
          duration_seconds: 3600
          role_session_name: 'helloworld@github-actions'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Terraform Plan
        run: |
          cd terraform 
          terraform init --backend-config=./backend/prod.hcl
          terraform plan -var-file=./env/prod.tfvars -out tf.plan

      - name: Terraform Apply
        run: |
          cd terraform 
          terraform apply -auto-approve tf.plan
